title: "Kangaroo: An OAuth2 Server"
email: krotscheck@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Kangaroo is an open source, multi-tenant, OAuth2 Authorization server. It fully supports RFC 6749
  (The original OAuth2 Specification), and aspires to be a reference implementation thereof.
  We intend to expand the scope of this project to include other OAuth2 related RFC's.

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://kangaroo-server.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  kangaroo-server

irc_channel: kangaroo

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
- documentation
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
